% Auto-generated by cameraCalibrator app on 25-Sep-2023
%-------------------------------------------------------
% Define images to process
imageFileNames = {'Images\image_0.png',...
    'Images\image_1.png',...
    'Images\image_2.png',...
    'Images\image_3.png',...
    'Images\image_4.png',...
    'Images\image_5.png',...
    'Images\image_6.png',...
    'Images\image_7.png',...
    'Images\image_9.png',...
    'Images\image_10.png',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 35;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% For use in OpenCV
[cameraMatrix,distortionCoefficients] = cameraIntrinsicsToOpenCV(cameraParams);
%save("arjunPC_camParams.mat", "cameraMatrix", "distortionCoefficients");
%save("arjunLaptop_camParams.mat", "cameraMatrix", "distortionCoefficients");
save("d455i_camParams.mat", "cameraMatrix", "distortionCoefficients");

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
